// Phase-1 Detailed Project Report figures, supplied directly by the client's
// architectural brief. See assets/documents/architectural-brief-phase1.md for
// the full source document.

export const campusStats = [
  { icon: "Ruler", value: "20.4", suffix: " Acres", label: "Total site area" },
  { icon: "Buildings", value: "8,000", suffix: " sq.m", label: "Permanent built-up area" },
  { icon: "ArrowsHorizontal", value: "550", suffix: "m", label: "Campus length" },
  { icon: "ArrowsVertical", value: "150", suffix: "m", label: "Campus width" },
];

export const mainBuilding = {
  name: "Main Building",
  configuration: "G+2",
  totalArea: "4,000 sq.m",
  floors: [
    {
      name: "Ground Floor",
      area: "1,500 sq.m",
      facilities: [
        {
          key: "grand-reception",
          icon: "DoorOpen",
          title: "Grand Reception",
          body: "The first impression of the campus — warm, welcoming, unmistakably premium.",
          image: "/images/jk-illust-d-cp-gf-reception.png",
          alt: "A brushed brass reception bell resting on a polished marble counter",
        },
        {
          key: "administrative-office",
          icon: "Briefcase",
          title: "Administrative Office",
          body: "The administrative heart of daily campus operations.",
          image: "/images/jk-illust-d-cp-gf-admin.png",
          alt: "A leather-bound ledger book with a brushed brass fountain pen",
        },
        {
          key: "board-room",
          icon: "UsersThree",
          title: "Board Room",
          body: "Where the campus's most important decisions are made.",
          image: "/images/jk-illust-d-cp-gf-board.png",
          alt: "An elegant crystal glass paperweight on a leather desk pad",
        },
        {
          key: "exhibition-gallery",
          icon: "Image",
          title: "Exhibition Gallery",
          body: "A rotating showcase of student work, research, and campus history.",
          image: "/images/jk-illust-d-cp-gf-exhibition.png",
          alt: "A small framed artwork resting on a wooden easel",
        },
        {
          key: "auditorium",
          icon: "Microphone",
          title: "Auditorium",
          body: "The venue for assemblies, performances, and campus-wide gatherings.",
          image: "/images/jk-illust-d-cp-gf-auditorium.png",
          alt: "Woven fabric seat cushions resting on a wooden bench",
        },
        {
          key: "dining-hall",
          icon: "ForkKnife",
          title: "Dining Hall",
          body: "Shared meals at the center of daily campus life.",
          image: "/images/jk-illust-d-cp-gf-dining.png",
          alt: "Ceramic dinner plates stacked with a folded linen napkin",
        },
        {
          key: "kitchen",
          icon: "CookingPot",
          title: "Kitchen",
          body: "Where the campus's sattvic meals are prepared fresh each day.",
          image: "/images/jk-illust-d-cp-gf-kitchen.png",
          alt: "A copper cooking pot with a wooden spoon resting against it",
        },
        {
          key: "medical-centre",
          icon: "FirstAidKit",
          title: "Medical Centre",
          body: "On-site medical care, close at hand for every resident.",
          image: "/images/jk-illust-d-cp-gf-medical.png",
          alt: "A glass medicine vial with a brass dropper cap on white linen",
        },
      ],
    },
    {
      name: "First Floor",
      area: "1,300 sq.m",
      facilities: [
        {
          key: "library-knowledge-centre",
          icon: "BookOpenText",
          title: "Library & Knowledge Centre",
          body: "A quiet home for study, research, and the printed word.",
          image: "/images/jk-illust-d-cp-ff-library.png",
          alt: "An antique brass library lamp beside a stack of hardcover books",
        },
        {
          key: "digital-learning-centre",
          icon: "Monitor",
          title: "Digital Learning Centre",
          body: "Technology-enabled learning spaces for the digital generation.",
          image: "/images/jk-illust-d-cp-ff-digital.png",
          alt: "A matte ceramic and glass digital display panel on a wood stand",
        },
        {
          key: "innovation-lab",
          icon: "Flask",
          title: "Innovation Lab",
          body: "A hands-on space for turning ideas into working prototypes.",
          image: "/images/jk-illust-d-cp-ff-innovation.png",
          alt: "A brushed brass gear mechanism resting on a stone surface",
        },
        {
          key: "research-centre",
          icon: "Microscope",
          title: "Research Centre",
          body: "Dedicated space for applied research across disciplines.",
          image: "/images/jk-illust-d-cp-ff-research.png",
          alt: "A glass petri dish with natural botanical leaf specimens",
        },
        {
          key: "faculty-rooms",
          icon: "ChalkboardTeacher",
          title: "Faculty Rooms",
          body: "Private space for faculty preparation and one-on-one mentoring.",
          image: "/images/jk-illust-d-cp-ff-faculty.png",
          alt: "A brushed brass letter-opener on a stack of handmade paper",
        },
        {
          key: "meeting-rooms",
          icon: "UsersThree",
          title: "Meeting Rooms",
          body: "Smaller spaces for focused discussion and collaboration.",
          image: "/images/jk-illust-d-cp-ff-meeting.png",
          alt: "A glass water carafe with a single tumbler on a wood table",
        },
      ],
    },
    {
      name: "Second Floor",
      area: "1,200 sq.m",
      facilities: [
        {
          key: "meditation-hall",
          icon: "PersonSimpleTaiChi",
          title: "Meditation Hall",
          body: "A dedicated space for daily stillness and inward practice.",
          image: "/images/jk-illust-d-cp-sf-meditation.png",
          alt: "A single lit incense stick in a ceramic holder with rising smoke",
        },
        {
          key: "yoga-hall",
          icon: "Plant",
          title: "Yoga Hall",
          body: "Where the campus's daily yoga and pranayama practice takes place.",
          image: "/images/jk-illust-d-cp-sf-yoga.png",
          alt: "A rolled linen yoga mat secured with a leather strap",
        },
        {
          key: "conference-hall",
          icon: "Microphone",
          title: "Conference Hall",
          body: "A larger venue for lectures, seminars, and visiting speakers.",
          image: "/images/jk-illust-d-cp-sf-conference.png",
          alt: "An elegant leather portfolio folder resting on a wood table",
        },
        {
          key: "skill-training-rooms",
          icon: "GraduationCap",
          title: "Skill Training Rooms",
          body: "Hands-on space for vocational and technical skill-building.",
          image: "/images/jk-illust-d-cp-sf-skill.png",
          alt: "Hand-carved wooden workshop tools arranged on canvas cloth",
        },
        {
          key: "spiritual-wisdom-centre",
          icon: "HandHeart",
          title: "Spiritual Wisdom Centre",
          body: "A space for study and reflection on the campus's spiritual traditions.",
          image: "/images/jk-illust-d-cp-sf-spiritual.png",
          alt: "An antique brass oil lamp with a soft glowing flame on stone",
        },
        {
          key: "vip-suites",
          icon: "Star",
          title: "VIP Suites",
          body: "Private accommodation for visiting dignitaries and guests.",
          image: "/images/jk-illust-d-cp-sf-vip.png",
          alt: "A folded luxury linen robe resting on a woven basket",
        },
      ],
    },
  ],
};

export const residentialBuildings = {
  count: 6,
  configuration: "G+1",
  eachArea: "600 sq.m",
  totalArea: "3,600 sq.m",
  uses: [
    {
      key: "students-living",
      icon: "House",
      title: "Students Living",
      body: "Comfortable, dignified residence for the student community.",
      image: "/images/jk-illust-d-cp-rb-students.png",
      alt: "A folded woven cotton blanket on a wooden bed frame corner",
    },
    {
      key: "faculty-residence",
      icon: "Buildings",
      title: "Faculty Residence",
      body: "On-campus housing for faculty, close to daily campus life.",
      image: "/images/jk-illust-d-cp-rb-faculty.png",
      alt: "A small ceramic vase with a single flower on a windowsill",
    },
    {
      key: "aaharshala-dining",
      icon: "ForkKnife",
      title: "Aaharshala (dining)",
      body: "Community dining at the heart of residential life.",
      image: "/images/jk-illust-d-cp-rb-aaharshala.png",
      alt: "A woven bread basket with fresh baked bread on linen",
    },
    {
      key: "students-activity-centre",
      icon: "UsersThree",
      title: "Students Activity Centre",
      body: "A shared space for games, hobbies, and downtime between classes.",
      image: "/images/jk-illust-d-cp-rb-activity.png",
      alt: "A wooden chess set with pieces mid-game on a stone table",
    },
    {
      key: "arogyashala-health",
      icon: "Heartbeat",
      title: "Arogyashala (health)",
      body: "Everyday wellness and preventive care within the residences.",
      image: "/images/jk-illust-d-cp-rb-arogyashala.png",
      alt: "A glass jar of natural honey with a wooden honey dipper",
    },
    {
      key: "natural-nutrition-centre",
      icon: "Carrot",
      title: "Natural Nutrition Centre",
      body: "Fresh, organic nutrition grown and prepared close to home.",
      image: "/images/jk-illust-d-cp-rb-nutrition.png",
      alt: "A wicker basket of fresh seasonal fruit on a wood table",
    },
    {
      key: "skill-development-centre-res",
      icon: "GraduationCap",
      title: "Skill Development Centre",
      body: "Vocational training woven into everyday residential life.",
      image: "/images/jk-illust-d-cp-rb-skill.png",
      alt: "A ball of cream wool yarn with wooden knitting needles",
    },
    {
      key: "research-innovation-centre-res",
      icon: "Flask",
      title: "Research & Innovation Centre",
      body: "A residential-side space for independent study and inquiry.",
      image: "/images/jk-illust-d-cp-rb-research.png",
      alt: "A brass telescope resting on a wooden tripod stand",
    },
  ],
};

export const utilityBuildings = {
  count: 4,
  configuration: "G+1",
  eachArea: "100 sq.m",
  totalArea: "400 sq.m",
  uses: [
    {
      key: "security-office",
      icon: "ShieldCheck",
      title: "Security Office",
      body: "Round-the-clock security coordination for the whole campus.",
      image: "/images/jk-illust-d-cp-ub-security.png",
      alt: "A brass vintage key ring with ornate keys on a wood surface",
    },
    {
      key: "electrical-room",
      icon: "Lightning",
      title: "Electrical Room",
      body: "The campus's core electrical distribution and backup systems.",
      image: "/images/jk-illust-d-cp-ub-electrical.png",
      alt: "A minimalist matte-metal circuit panel form on stone",
    },
    {
      key: "telecom-room",
      icon: "WifiHigh",
      title: "Telecom Room",
      body: "Connectivity infrastructure keeping the campus online.",
      image: "/images/jk-illust-d-cp-ub-telecom.png",
      alt: "An abstracted minimalist antenna form in brushed matte metal",
    },
    {
      key: "maintenance-office",
      icon: "Wrench",
      title: "Maintenance Office",
      body: "The base for the team that keeps every building running.",
      image: "/images/jk-illust-d-cp-ub-maintenance.png",
      alt: "Brass wrenches arranged neatly on a wood workbench",
    },
    {
      key: "store-room",
      icon: "Package",
      title: "Store Room",
      body: "Central storage supporting daily campus operations.",
      image: "/images/jk-illust-d-cp-ub-store.png",
      alt: "Stacked wooden storage crates tied with natural rope",
    },
    {
      key: "food-courts",
      icon: "ForkKnife",
      title: "Food Courts",
      body: "Everyday dining options beyond the main dining hall.",
      image: "/images/jk-illust-d-cp-ub-food.png",
      alt: "A wooden serving tray with a ceramic bowl and cup",
    },
    {
      key: "wash-rooms",
      icon: "Drop",
      title: "Wash Rooms",
      body: "Clean, well-maintained facilities across every building.",
      image: "/images/jk-illust-d-cp-ub-wash.png",
      alt: "Folded white linen towels beside a ceramic basin",
    },
    {
      key: "horticulture-office",
      icon: "Plant",
      title: "Horticulture Office",
      body: "Coordinating the care of gardens and green spaces campus-wide.",
      image: "/images/jk-illust-d-cp-ub-horticulture.png",
      alt: "A terracotta plant pot with garden shears resting beside it",
    },
  ],
};

export const grandEntrance = [
  {
    key: "monumental-gate",
    icon: "DoorOpen",
    title: "Monumental Gate",
    body: "The campus's grand, unmistakable point of arrival.",
    image: "/images/jk-illust-d-cp-ge-gate.png",
    alt: "A miniature architectural model of a ceremonial monumental gate",
  },
  {
    key: "security-check",
    icon: "ShieldCheck",
    title: "Security Check",
    body: "A calm, orderly checkpoint for every visitor and vehicle.",
    image: "/images/jk-illust-d-cp-ge-security.png",
    alt: "A brass security badge resting on a stone counter",
  },
  {
    key: "visitor-parking",
    icon: "Garage",
    title: "Visitor Parking",
    body: "Dedicated parking so arrival is simple from the very first minute.",
    image: "/images/jk-illust-d-cp-ge-parking.png",
    alt: "A miniature architectural model of a marked parking area",
  },
  {
    key: "digital-display",
    icon: "Monitor",
    title: "Digital Display",
    body: "Real-time information greeting every visitor at the gate.",
    image: "/images/jk-illust-d-cp-ge-display.png",
    alt: "A minimalist frosted glass display panel on a metal stand",
  },
  {
    key: "reception-plaza",
    icon: "Path",
    title: "Reception Plaza",
    body: "An open gathering space that sets the tone before you even step inside.",
    image: "/images/jk-illust-d-cp-ge-plaza.png",
    alt: "A miniature architectural model of a plaza with a central fountain",
  },
];

export const sustainableInfrastructure = {
  landscape: [
    { icon: "TreeEvergreen", label: "Native trees" },
    { icon: "TreeEvergreen", label: "Fruit orchard" },
    { icon: "Plant", label: "Medicinal plants" },
    { icon: "TreeEvergreen", label: "Bamboo plantation" },
    { icon: "Sparkle", label: "Flower gardens" },
    { icon: "Butterfly", label: "Butterfly garden" },
  ],
  greenInfrastructure: [
    { icon: "SunHorizon", label: "Solar Power Plant" },
    { icon: "CloudRain", label: "Rain Water Harvesting" },
    { icon: "Recycle", label: "Sewage Treatment Plant (STP)" },
    { icon: "Leaf", label: "Organic Waste Compost Plant" },
    { icon: "Drop", label: "Drip Irrigation" },
    { icon: "ArrowsClockwise", label: "Grey Water Recycling" },
    { icon: "ChargingStation", label: "EV Charging" },
    { icon: "Lightbulb", label: "Smart Lighting" },
  ],
};

export const roads = [
  { icon: "Path", label: "12 m Main Road" },
  { icon: "Path", label: "6 m Internal Roads" },
  { icon: "PersonSimpleWalk", label: "Walking Track" },
  { icon: "Bicycle", label: "Cycling Track" },
  { icon: "HandHeart", label: "Disabled-friendly pathways" },
];

export const waterFeatures = [
  { icon: "Drop", label: "Central Fountain" },
  { icon: "FlowerLotus", label: "Lotus Pond" },
  { icon: "Waves", label: "Water Bodies" },
  { icon: "CloudRain", label: "Recharge Pits" },
];

export const parking = [
  { icon: "Garage", label: "Visitors" },
  { icon: "Briefcase", label: "Staff" },
  { icon: "GraduationCap", label: "Students" },
  { icon: "ChargingStation", label: "Electric Vehicle Charging" },
];

export const futureExpansion = {
  area: "4,000 sq.m",
  items: [
    { icon: "GridFour", label: "Modular structures" },
    { icon: "ChalkboardTeacher", label: "Training halls" },
    { icon: "House", label: "Dormitories" },
    { icon: "Wrench", label: "Workshops" },
    { icon: "Rocket", label: "Startup incubation" },
  ],
};
